language: elixir
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 18.0
  - 19.0
  - 20.0

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
    - elixir: 1.6
      otp_release: 18.0

after_script:
  - mix coveralls.travis
